---

name:
    sitemap-gen
version:
    0.1.0.0
synopsis:
    "Generate XML Sitemaps & Sitemap Indexes"
github:
    prikhi/sitemap-gen
license:
    BSD3
license-file:
    LICENSE
author:
    Pavan Rikhi
maintainer:
    pavan.rikhi@gmail.com
copyright:
    2019 - 2021, Pavan Rikhi
category:
    Web
extra-source-files:
    - README.md
    - CHANGELOG.md
description: |
    The @sitemap-gen@ package uses the @xmlgen@ package to generate XML
    sitemaps that are compliant with the sitemaps.org XML schema.

    See the "Web.Sitemap.Gen" module and the
    <https://github.com/prikhi/sitemap-gen/blob/master/README.md README> file
    for documentation & usage details.

dependencies:
    - base >= 4.7 && < 5

library:
    source-dirs:
        src
    ghc-options:
        - -Wall
        - -Wcompat
        - -Wincomplete-record-updates
        - -Wincomplete-uni-patterns
        - -Wredundant-constraints
    dependencies:
        - text >= 1 && < 2
        - time >= 1.6 && < 2
        - xmlgen >= 0.6 && < 1


tests:
    sitemap-gen-tests:
        main:
            Spec.hs
        source-dirs:
            tests
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - sitemap-gen
            - bytestring
            - HUnit
            - tasty
            - tasty-hunit
            - time
            - raw-strings-qq
